### ISSUE TITLE
updated?

### ISSUE THREAD

**Issue by bobbler321** [zyhp/vac3_inhibitor#12]
I know there were some "unknown modules" but as I was messing around with it I noticed that there were no [ VAC3 ] notifications in the console. I also get "vac unable to verify game session". I'm wondering if this is outdated or if I'm just retarded keep in mind I know jack shit about coding.

**Comment by blxckshark** [comment]
> I know there were some "unknown modules" but as I was messing around with it I noticed that there were no [ VAC3 ] notifications in the console. I also get "vac unable to verify game session". I'm wondering if this is outdated or if I'm just retarded keep in mind I know jack shit about coding.

Some news, does it works?

**Comment by bobbler321** [comment]
¯\_(ツ)_/¯ I just started using the other vac bypass until a new pull request is made, just to be on the safe side

**Comment by blxckshark** [comment]
> ¯_(ツ)_/¯ I just started using the other vac bypass until a new pull request is made, just to be on the safe side

link please?

**Comment by bobbler321** [comment]
> > ¯_(ツ)_/¯ I just started using the other vac bypass until a new pull request is made, just to be on the safe side
> 
> link please?
> And actually, this shit is outdated, we need new patterns.

https://github.com/danielkrupinski/VAC-Bypass

**Comment by zyhp** [comment]
Duplicate of #10
