### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by aldias14** [zyhp/vac3_inhibitor#20]
When I run it, the console opens and nothing else happens, writes "ready", but there are no additional messages like: "[ VAC3 ] ready...". Can you check if it works now, is vac updated? Can you help pls?

**Comment by TungstenWolf** [comment]
Thats what im wondering, i dont wanna test in fear of getting a ban and they did update vac i heard (could be a rumor)

**Comment by april2202** [comment]
It should be working as the signature didn't change and it still hooking fine
