### ISSUE TITLE
STEAM Path

### ISSUE THREAD

**Issue by AlexanderQueen** [zyhp/vac3_inhibitor#7]
I used MessageBox as invoking errors and success messages, how to stop invoking each time cmd line? Strings i replaced in message box. But can't figure out how to call steam_path without calling cmd line, like in silent mode.

**Comment by zyhp** [comment]
Excuse me but, what?

You changed std::cout to MessageBox from what i understand, and you can't display _steam_path_ variable? It's a std::string and MessageBoxA takes in a LPCSTR... just do steam_path.c_str() and it will work,

`MessageBox( nullptr, steam_path.c_str(), "", MB_OK );`

**Comment by AlexanderQueen** [comment]
Nah, everytime i launch it launches cmd+box, i need only messagebox.

**Comment by zyhp** [comment]
Oh...

Please use google for the basic stuff... You can find your answer in under 1 minute.

**Comment by AlexanderQueen** [comment]
It will take an eternity....
