### ISSUE TITLE
I think VAC got an update but not sure

### ISSUE THREAD

**Issue by eren-erver** [zyhp/vac3_inhibitor#8]
When I used vac3_inhibitor for csgo. It worked well with no errors but after a while , I saw [VAC3] Unknown module loaded in steam console. I think there's a new module.

**Comment by ShapeShifterZ** [comment]
it shouldn't be a problem for now. 

You have to find a dumper to dump the VAC3 Modules with and update them. If you find one lmk Saikyo#0345 because I couldn't find any that ARE MEANT to be used on windows.

**Comment by 59g** [comment]
check pull requests.

**Comment by 59g** [comment]
@eren-erver

**Comment by bobbler321** [comment]
i know absolutely nothing about coding but i also noticed the unknown module, explain what you mean by "check pull requests"

**Comment by eren-erver** [comment]
It means you should download the project file from here : https://github.com/zyhp/vac3_inhibitor/tree/0eaeec3033d536871a12ec69c1919dcb256210fa and compile it by yourself using visual studio. If you don't want to compile I have a compiled version but compile it by yourself because I am just a stranger from github don't download files from strangers.

**Comment by bobbler321** [comment]
ok i have tried to compile it but every time i try i have gotten157 errors

**Comment by snajdovski** [comment]
> 
> 
> ok i have tried to compile it but every time i try i have gotten157 errors

You need to Use C++ 2017 Compiler (README) , Visual Studio Uses older C++ compiler by default I think.

**Comment by bobbler321** [comment]
Thank you @snajdovski it worked perfectly

**Comment by batininhani** [comment]
@59g Outdated

**Comment by blxckshark** [comment]
we need update :(

**Comment by blxckshark** [comment]
@snajdovski

**Comment by 59g** [comment]
wdym update it works fine
